name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push runner
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jojoc4/lsbs-runner:latest
          file: Benchmark-runner/Dockerfile
      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jojoc4/lsbs-front:latest
          file: Frontend/Dockerfile
      - name: Build and push api
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jojoc4/lsbs-api:latest
          file: Benchmark-api/Dockerfile
      - name: Build and push iperf
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jojoc4/lsbs-iperf:latest
          file: Benchmarks/files/iperf/Dockerfile
